// Offline quote pool, used when the quote API is unreachable or its quotes have all been asked.
// Loaded with a <script> tag so the game also works when opened via file://
const QUOTE_DATA = [
  // From the quote API pool
  { "character": "Portgas D. Ace", "quote": "I don't wanna live a thousand years. If I just live through today, that'll be enough." },
  { "character": "Portgas D. Ace", "quote": "Sometimes, the blood rushes to my head and I feel like, if I run, I'll lose something important." },
  { "character": "Portgas D. Ace", "quote": "Old man, everyone!! And you.. Luffy. Even though I've been good for nothing my whole life, even though I have the blood of a demon within me... You guys still loved me! Thank you so much!!" },
  { "character": "Portgas D. Ace", "quote": "We have to live a life of no regrets." },
  { "character": "Dracule Mihawk", "quote": "You are defeated yet you will not step back, why not?" },
  { "character": "Dracule Mihawk", "quote": "I'm not stupid enough to use a cannon to hunt a rabbit." },
  { "character": "Monkey D. Luffy", "quote": "Being alone is more painful than getting hurt." },
  { "character": "Monkey D. Luffy", "quote": "Forgetting is like a wound. The wound may heal but it has already left a scar." },
  { "character": "Monkey D. Luffy", "quote": "If you don't risk your life, you can't create a future. Right?" },
  { "character": "Monkey D. Luffy", "quote": "No matter how hard or impossible it is, never lose sight of your goal." },
  { "character": "Monkey D. Luffy", "quote": "Hero? No! We're pirates! I love heroes, but I don't wanna be one! Do you know what heroes are? Say there is a chunk of meat. Pirates will have a banquet and eat it, but heroes will share it with other people. I want all the meat!" },
  { "character": "Monkey D. Luffy", "quote": "So, you don't like to get hit, huh? Well, you're about to have a very bad day." },
  { "character": "Monkey D. Luffy", "quote": "Are we friends? Or are we foes? That kind of thing you decide for yourselves!" },
  { "character": "Crocodile", "quote": "\"If I do this, I can stop the rebellion\", \"if I do that, I can stop the rebellion\"... Open your eyes, princess! Your zealous idealism disgusts me! Ideals can only be spoken by those powerful enough to carry them out. And that excludes you!" },
  { "character": "Crocodile", "quote": "Wake up princess, I'm tired of your useless ideals. It's gotten pathetic. What good are your happy ideals if you can't do anything to make them a reality? They're nothing but dreams, and your dreams don't stand a chance." },
  { "character": "Gol D. Roger", "quote": "The world...what a glorious place! Seek freedom, and it will lie stretched out before your eyes. If the endless dream guides your restless spirit, seize it! Raise your flag, and stand tall!" },
  { "character": "Arlong", "quote": "Living is important! It is because one lives, one can enjoy things! Everyone has their own designated place and position in life! This man understands the futility of resisting against that fact! You see, not all living things, are born equal!" },
  { "character": "Smoker", "quote": "Why did he smile? Why? Did he know he would be saved? No. In that instant, he must have understood that his life was going to end. Death. He accepted it. He was fully prepared for it and smiled." },
  { "character": "Smoker", "quote": "Don't ever think there's any perfect society made by humans!! If you think that way you'll overlook the enemy!! Don't be fooled by appearances!!" },
  { "character": "Sanji", "quote": "Don't start a fight if you can't end it." },
  { "character": "Sanji", "quote": "I couldn't confess my feelings for you, so I watched you from afar, being happy with someone else." },
  { "character": "Sanji", "quote": "A real man is someone who forgives a woman for her lies!" },
  { "character": "Trafalgar Law", "quote": "You can't see the whole picture until you look at it from the outside." },
  { "character": "Trafalgar Law", "quote": "There are things you can't see unless you change your standing." },
  { "character": "Usopp", "quote": "I'm the sniper king, sogeking." },
  { "character": "Usopp", "quote": "When I left Syrup Village, I left everything behind! Tranquility… Safety… They face hardships every day, and they laugh like they're really having fun! That's why I decided to go out to sea! I want to laugh 'til I cry, too! But if I don't fight with everything I've got, there's no way I deserve to be on the same boat as them! There's no way I can laugh with them!" },
  { "character": "Nico Robin", "quote": "Fools who don't respect the past are likely to repeat it." },
  { "character": "Nico Robin", "quote": "Before the heart of truth, there is no need for words." },
  { "character": "Roronoa Zoro", "quote": "You want to kill me? You couldn't even kill my boredom!" },
  { "character": "Roronoa Zoro", "quote": "I don't care what the society says. I've regretted doing anything. I will survive and do what I want to." },
  { "character": "Roronoa Zoro", "quote": "Only those who have suffered long, can see the light within the shadows" },
  { "character": "Roronoa Zoro", "quote": "I'm a pirate hunter." },
  { "character": "Jinbe", "quote": "You can't bring back what you've lost, think about what you have now!" },
  { "character": "Fujitora", "quote": "If you lose credibility by just admitting fault, then you didn't have any in the first place." },
  { "character": "Kizaru", "quote": "Without strength, you won't be able to save anyone." },
  { "character": "Tony Tony Chopper", "quote": "I want a devil fruit." },
  { "character": "Rayleigh", "quote": "Maybe nothing in this world happens by accident. As everything happens for a reason, our destiny slowly takes form..." },
  { "character": "Brook", "quote": "Neither God nor the Devil can give aid to those without the will to fight…" },
  { "character": "Eustass Kid", "quote": "Compared to the \"righteous\" greed of the rulers, the criminals of the world seem much more honorable. When scum rules the world, only more scum is born." },
  { "character": "Nami", "quote": "Life is like a pencil that will surely run out, but will leave the beautiful writing of life." },
  { "character": "Donquixote Doflamingo", "quote": "The time is almost here. Go and lay the groundwork. A world where only true pirates can survive will soon be upon us. Those without power, flee while you can. The tide will bring those of unmatched power and the New Era will begin!" },
  { "character": "Donquixote Doflamingo", "quote": "There is a difference in the look of the ordinary vagabond and that of a determined man." },
  { "character": "Boa Hancock", "quote": "Whether I kick a kitten... Tear off your ears... Even slaughter innocent people... The world will never cease to forgive my actions! Why, you ask? That's right, it is because I am... Beautiful!!!" },

  // Well-known lines added to widen the pool (wording may differ slightly between translations)
  { "character": "Monkey D. Luffy", "quote": "I don't want to conquer anything. I just think the guy with the most freedom in this whole ocean is the Pirate King!" },
  { "character": "Monkey D. Luffy", "quote": "Power isn't determined by your size, but the size of your heart and dreams!" },
  { "character": "Roronoa Zoro", "quote": "When the world shoves you around, you just gotta stand up and shove back. It's not like somebody's gonna save you if you start babbling excuses." },
  { "character": "Roronoa Zoro", "quote": "Nothing... happened." },
  { "character": "Sanji", "quote": "I'd rather die than kick a woman!" },
  { "character": "Nami", "quote": "Luffy... help me..." },
  { "character": "Nico Robin", "quote": "I want to live! Take me out to sea with you!" },
  { "character": "Usopp", "quote": "I've got a terrible disease called 'I-can't-go-to-this-island' disease!" },
  { "character": "Tony Tony Chopper", "quote": "I'm not a raccoon dog, I'm a reindeer!" },
  { "character": "Brook", "quote": "May I see your panties?" },
  { "character": "Shanks", "quote": "I bet my arm on the new era." },
  { "character": "Edward Newgate", "quote": "The One Piece... is real!" },
  { "character": "Gol D. Roger", "quote": "My treasure? If you want it, you can have it! Look for it! I left everything in that one place!" },
  { "character": "Hiluluk", "quote": "When do you think people die? When they are shot through the heart by a pistol? No. When they are ravaged by an incurable disease? No. It's when they are forgotten." },
  { "character": "Donquixote Doflamingo", "quote": "Pirates are evil? The Marines are righteous? These terms have always changed throughout the course of history! Whoever wins this war becomes justice!" },
  { "character": "Blackbeard", "quote": "People's dreams... never end!" },
  { "character": "Enel", "quote": "I am God!" },
  { "character": "Big Mom", "quote": "Life or treat?" },
  { "character": "Kizaru", "quote": "Have you ever been kicked at the speed of light?" },
  { "character": "Yamato", "quote": "I am Kozuki Oden!" },
  { "character": "Corazon", "quote": "Law... I love you!" }
];
